# compose.yml
version: '3'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py # Substitua 'app.py' pelo nome do seu script principal Flask
